on:
  push:
    branches:
      - master
name: Build the docker container
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: convert-repository
        name: Convert repository name to lowercase
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker buildx build -f Dockerfile . --tag ghcr.io/${{ steps.convert-repository.outputs.lowercase }}:latest --platform linux/amd64,linux/arm64 --push
